// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/std/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Student              []*Student             `protobuf:"bytes,1,rep,name=student,proto3" json:"student,omitempty"`
	Acceptleaverequest   []AcceptLeaveRequest   `protobuf:"bytes,2,rep,name=acceptleaverequest,proto3" json:"acceptleaverequest"`
	Applyleaverequest    []ApplyLeaveRequest    `protobuf:"bytes,3,rep,name=applyleaverequest,proto3" json:"applyleaverequest"`
	Registeradminrequest []RegisterAdminRequest `protobuf:"bytes,4,rep,name=registeradminrequest,proto3" json:"registeradminrequest"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa56e19892dd34e5, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetStudent() []*Student {
	if m != nil {
		return m.Student
	}
	return nil
}

func (m *GenesisState) GetAcceptleaverequest() []AcceptLeaveRequest {
	if m != nil {
		return m.Acceptleaverequest
	}
	return nil
}

func (m *GenesisState) GetApplyleaverequest() []ApplyLeaveRequest {
	if m != nil {
		return m.Applyleaverequest
	}
	return nil
}

func (m *GenesisState) GetRegisteradminrequest() []RegisterAdminRequest {
	if m != nil {
		return m.Registeradminrequest
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "cosmos.std.v1beta1.GenesisState")
}

func init() { proto.RegisterFile("cosmos/std/v1beta1/genesis.proto", fileDescriptor_fa56e19892dd34e5) }

var fileDescriptor_fa56e19892dd34e5 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd1, 0x31, 0x6b, 0xc2, 0x40,
	0x14, 0xc0, 0xf1, 0x44, 0xa5, 0x85, 0xb3, 0x4b, 0x0f, 0x07, 0x51, 0xb8, 0x4a, 0xc1, 0xe2, 0x94,
	0x60, 0x4b, 0x3f, 0x80, 0x2e, 0x5d, 0x3a, 0xc5, 0xa9, 0xa5, 0xcb, 0x25, 0x79, 0x84, 0x80, 0xe6,
	0xae, 0x79, 0x4f, 0xd1, 0x6f, 0xd1, 0x8f, 0xe5, 0xe8, 0xd8, 0xa9, 0x94, 0xe4, 0x8b, 0x48, 0xee,
	0x74, 0x10, 0x6f, 0x3b, 0x8e, 0xff, 0xfb, 0xbd, 0xe1, 0xb1, 0x51, 0xa2, 0x70, 0xa5, 0x30, 0x44,
	0x4a, 0xc3, 0xcd, 0x34, 0x06, 0x92, 0xd3, 0x30, 0x83, 0x02, 0x30, 0xc7, 0x40, 0x97, 0x8a, 0x14,
	0xe7, 0xb6, 0x08, 0x90, 0xd2, 0xe0, 0x54, 0x0c, 0x86, 0x8e, 0x29, 0xda, 0xda, 0x81, 0x41, 0x2f,
	0x53, 0x99, 0x32, 0xcf, 0xb0, 0x79, 0xd9, 0xdf, 0xc7, 0xaa, 0xc5, 0xee, 0xde, 0x2c, 0xbc, 0x20,
	0x49, 0xc0, 0x5f, 0xd9, 0x2d, 0xd2, 0x3a, 0x85, 0x82, 0xfa, 0xfe, 0xa8, 0x3d, 0xe9, 0x3e, 0x0f,
	0x83, 0xeb, 0x4d, 0xc1, 0xc2, 0x26, 0xd1, 0xb9, 0xe5, 0x5f, 0x8c, 0xcb, 0x24, 0x01, 0x4d, 0x4b,
	0x90, 0x1b, 0x28, 0xe1, 0x7b, 0x0d, 0x48, 0xfd, 0x96, 0x11, 0x9e, 0x5c, 0xc2, 0xcc, 0xd4, 0xef,
	0x4d, 0x1d, 0xd9, 0x7a, 0xde, 0xd9, 0xff, 0x3d, 0x78, 0x91, 0xc3, 0xe1, 0x1f, 0xec, 0x5e, 0x6a,
	0xbd, 0xdc, 0x5d, 0xe0, 0x6d, 0x83, 0x8f, 0x9d, 0x78, 0x13, 0x3b, 0xec, 0x6b, 0x85, 0xc7, 0xac,
	0x57, 0x42, 0x96, 0x23, 0x41, 0x29, 0xd3, 0x55, 0x5e, 0x9c, 0xf5, 0x8e, 0xd1, 0x27, 0x2e, 0x3d,
	0x3a, 0xf5, 0xb3, 0xa6, 0xbf, 0x5c, 0xe0, 0xb4, 0xe6, 0xe3, 0x7d, 0x25, 0xfc, 0x43, 0x25, 0xfc,
	0xff, 0x4a, 0xf8, 0x3f, 0xb5, 0xf0, 0x0e, 0xb5, 0xf0, 0x7e, 0x6b, 0xe1, 0x7d, 0x76, 0xb7, 0xe6,
	0x58, 0xb4, 0xd3, 0x80, 0xf1, 0x8d, 0x39, 0xc9, 0xcb, 0x31, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xbb,
	0xac, 0x07, 0xfd, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Registeradminrequest) > 0 {
		for iNdEx := len(m.Registeradminrequest) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Registeradminrequest[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Applyleaverequest) > 0 {
		for iNdEx := len(m.Applyleaverequest) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Applyleaverequest[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Acceptleaverequest) > 0 {
		for iNdEx := len(m.Acceptleaverequest) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Acceptleaverequest[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Student) > 0 {
		for iNdEx := len(m.Student) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Student[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Student) > 0 {
		for _, e := range m.Student {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Acceptleaverequest) > 0 {
		for _, e := range m.Acceptleaverequest {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Applyleaverequest) > 0 {
		for _, e := range m.Applyleaverequest {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Registeradminrequest) > 0 {
		for _, e := range m.Registeradminrequest {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Student", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Student = append(m.Student, &Student{})
			if err := m.Student[len(m.Student)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Acceptleaverequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Acceptleaverequest = append(m.Acceptleaverequest, AcceptLeaveRequest{})
			if err := m.Acceptleaverequest[len(m.Acceptleaverequest)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Applyleaverequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Applyleaverequest = append(m.Applyleaverequest, ApplyLeaveRequest{})
			if err := m.Applyleaverequest[len(m.Applyleaverequest)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registeradminrequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Registeradminrequest = append(m.Registeradminrequest, RegisterAdminRequest{})
			if err := m.Registeradminrequest[len(m.Registeradminrequest)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
